"""
Simple reporter for creating detailed reports
"""
import pandas as pd
from typing import Dict, Any


def create_detailed_report(results: Dict[str, Any]) -> str:
    """Create a simple detailed report"""
    report = []
    
    report.append("# Forecast Analysis Report")
    report.append("=" * 40)
    report.append("")
    
    if 'item_loc_id' in results:
        report.append(f"**Part Number:** {results['item_loc_id']}")
        
    if 'detected_issues' in results:
        issues = results['detected_issues']
        if issues:
            report.append(f"**Issues Detected:** {len(issues)}")
            for issue in issues:
                report.append(f"- {issue['type'].replace('_', ' ').title()}: {issue['description']}")
        else:
            report.append("**Status:** No issues detected")
            
    if 'risk_score' in results:
        report.append(f"**Risk Score:** {results['risk_score']:.2f}")
        
    report.append("")
    report.append("*Generated by Forecast Monitor Agent*")
    
    return "\n".join(report)